### ISSUE TITLE
Create a plan for designing and building the game

### ISSUE THREAD

**Issue by mobyvb** [mobyvb/download-simulator-2023#1]
Download Simulator is a 2D platforming game with controls and feel similar to Super Meat Boy.
A single level takes place in rectangular bounds, with a horizontal:vertical ratio of about 3:1. The level represents a "download bar", which is green and moves from the leftmost edge to the rightmost edge of the bounds.
The player starts near the left side of the level and attempts to navigate to a "safe zone" on the right side, and must navigate around obstacles to enter the safe zone without the green download bar touching them.
It should be easy to design levels in some sort of GUI
The player's score for a level is the amount of time it takes them to reach the safe zone
Write an action plan that breaks these requirements down into specific tasks that can each be worked on independently.
Order the items in the action plan based on which tasks would have the highest impact.
At the bottom of the action plan, add a section called "Open Questions", and insert a minimum of three possible complications or areas that might need further investigation. 

---

files: actionplan.md

**Comment by black-crowned-night-heron** [comment]
working on it
